export const LOCALE: string = 'ru';

export const TRANSLATES: Record<string, Record<string, string>> = {
  ru: {
    сonsumables: 'Расходные материалы',
    disposableConsumables: 'Одноразовые расходные материалы',
    popularCategories: 'Популярные категории',
    сonsumablesWholesaleRetail: 'Расходные материалы оптом и в розницу',
    gotoCreateOrder: 'Перейти к оформлению',
    favouriteProducts: 'Избранные товары',
    createOrderHint: 'Доступные способы доставки и оплаты можно выбрать при оформлении заказа',
    allCategories: 'Весь каталог',
    youViewed: 'Вы просматривали',
    main: 'Главная',
    general: 'Основное',
    category: 'Категория',
    catalog: 'Каталог',
    productsCatalog: 'Каталог продукции',
    product: 'Продукт',
    products: 'Продукты',
    delivery: 'Доставка',
    contacts: 'Контакты',
    preview: 'Просмотр',
    requestCall: 'Заказать звонок',
    getDetails: 'Узнать подробнее',
    send: 'Отправить',
    yourName: 'Ваше имя',
    name: 'Имя',
    enterName: 'Введите имя',
    phone: 'Телефона',
    enterPhone: 'Введите телефон',
    search: 'Поиск',
    byPrice: 'По цене',
    productsOnThePage: 'товаров на странице',
    showBy: 'Показывать по',
    requestCallSended: 'Наши операторы свяжутся с вами',
    ourAdvantages: 'Наши преимущества',
    deliveryAdvantage: 'Бесплатная доставка по Могилеву при заказе от 80р',
    intoCart: 'В корзину',
    amount: 'Количество',
    enter: 'Войти',
    password: 'Пароль',
    invalidLoginOrPassword: 'Неправильный логин или пароль',
    fieldRequired: 'Обязательное поле',
    invalidPrice: 'Неправильная цена',
    fieldInvalid: 'Неверное значение',
    editor: 'Редактор',
    save: 'Сохранить',
    buyInOneClick: 'Купить в 1 клик',
    alreadyInCart: 'В корзине',
    goto: 'перейти',
    information: 'Информация',
    mainShopInfo: 'Основная информация о магазине',
    enterMainShopInfo: 'Введите информацию о магазине',
    infoSaved: 'Информация сохранена',
    title: 'Название',
    enterTitle: 'Введите название',
    picture: 'Изображение',
    images: 'Картинки',
    selectImage: 'Выберите картинку',
    image: 'Картинка',
    imageDeleted: 'Картинка удалена',
    categoryDeleted: 'Категория удалена',
    somethingWentWrong: 'Что-то пошло не так =(',
    imagesUploaded: 'Картинки загружены',
    noImages: 'Картинок нет',
    chooseFiles: 'Выберите файлы',
    categories: 'Категории',
    subcategories: 'Подкатегории',
    add: 'Добавить',
    newCategory: 'Новая категория',
    newProduct: 'Новый продукт',
    update: 'Обновить',
    price: 'Цена',
    priceWithExamples: 'Цена(пример: 10; 12.20; 13.34)',
    enterLabel: "Введите Лейбл",
    label: "Лейбл",
    vendorCode: 'Артикул',
    enterVendorCode: 'Введите артикул',
    enterPrice: 'Введите цену',
    noCategories: 'Категорий нет',
    productDeleted: 'Продукт удален',
    description: 'Описание',
    enterDescription: 'Введите описание',
    workingHours: 'Время работы',
    enterWorkingHours: 'Введите время работы',
    emptyCart: 'Корзина пуста',
    thereAreNoFavouritesProducts: 'В избранном пусто',
    addToFavouritesHint: 'Выберите в каталоге интересующий товар и нажмите на ',
    purchaseCart: 'Корзина покупок',
    productName: 'Наименование товара',
    naming: 'Наименование',
    cleanFavourites: 'Очистить избранное',
    cleanCart: 'Очистить корзину',
    returnToCart: '← Вернуться в корзину',
    placeOrder: 'Оформление заказа',
    favourites: 'Избранное',
    productAdded: 'Продукт добавлен',
    shortAmountText: 'Кол-во',
    priceForOneProduct: 'Цена за шт.',
    all: 'Всего',
    result: 'Итого',
    intoCatalog: 'В каталог',
    delete: 'Удалить',
    currency: 'Валюта',
    enterCurrency: 'Введите валюту',
    createOrder: 'Оформить заказ',
    confirmOrder: 'Подтвердить заказ',
    order: 'Заказ',
    address: 'Адрес',
    enterAddress: 'Введите адрес',
    comment: 'Комментарий',
    clickCtrlForMultipleSelect: 'Нажмите ctrl для выбора нескольких',
    orderCreatedSuccessfully: 'Ваш заказ принят. Наши операторы свяжутся с вами',
    infoUpdated: 'Информация обновлена',
    deliveryDescription: 'Описание по доставке',
    addDeliveryDescription: 'Введите описание по доставке',
    addShopRegistrationDescription: 'Введите регистрационные данные',
    shopRegistrationDescription: 'Регистрационные данные',
    returnToCatalog: "Вернуться к каталогу товаров",
  }
}