export const LOCALE: string = 'ru';

export const TRANSLATES: Record<string, Record<string, string>> = {
  ru: {
    сonsumables: 'Расходные материалы',
    сonsumablesWholesaleRetail: 'Расходные материалы оптом и в розницу',
    aboutUsDescription: 'Наша компания на рынке более 5 лет и за это время мы сумели себя хорошо зарекомендовать. Мы работаем, чтобы обеспечить специалистов с сфере красоты и здоровья всем необходимым для качественной и безопасной работы. Прямые поставки от заводов- производителей позволяют нам предлагать своим клиентам только самые выгодные предложения и лучшие цены.',
    main: 'Главная',
    general: 'Основное',
    category: 'Категория',
    product: 'Продукт',
    products: 'Продукты',
    delivery: 'Доставка',
    contacts: 'Контакты',
    requestCall: 'Заказать звонок',
    send: 'Отправить',
    yourName: 'Ваше имя',
    phone: 'Телефона',
    search: 'Поиск',
    requestCallSended: 'Наши операторы свяжутся с вами',
    advantages: 'Преимущества',
    deliveryAdvantage: 'Бесплатная доставка по Могилеву при заказе от 80р',
    intoCart: 'В корзину',
    amount: 'Количество',
    enter: 'Войти',
    password: 'Пароль',
    invalidLoginOrPassword: 'Неправильный логин или пароль',
    fieldRequired: 'Обязательное поле',
    fieldInvalid: 'Неверное значение',
    editor: 'Редактор',
    save: 'Сохранить',
    mainShopInfo: 'Основная информация о магазине',
    infoSaved: 'Информация сохранена',
    title: 'Название',
    images: 'Картинки',
    selectImage: 'Выберите картинку',
    imageDeleted: 'Картинка удалена',
    categoryDeleted: 'Категория удалена',
    somethingWentWrong: 'Что-то пошло не так =(',
    imagesUploaded: 'Картинки загружены',
    noImages: 'Картинок нет',
    chooseFiles: 'Выберите файлы',
    categories: 'Категории',
    subcategories: 'Подкатегории',
    add: 'Добавить',
    newCategory: 'Новая категория',
    newProduct: 'Новый продукт',
    update: 'Обновить',
    price: 'Цена',
    noCategories: 'Категорий нет',
    productDeleted: 'Продукт удален',
    description: 'Описание',
    workingHours: 'Время работы',
    emptyCart: 'Корзина пуста',
  }
}